import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Narbar from "@/components/narbar";

const geisFiraCode = Fira_Code({
  variable : "--font-fira-code",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "bdhamithkumara",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geisFiraCode.variable} antialiased min-h-screen bg-gradient-to-br from-[#010c15] via-[#011627] to-[#1e2d3d] text-[#e5e9f0] font-mono `}
      >
        <Narbar/>
        {children}
      </body>
    </html>
  );
}
